package academy.tochkavhoda.school;

public enum TrainingErrorCode {
    TRAINEE_WRONG_FIRSTNAME,
    TRAINEE_WRONG_LASTNAME,
    TRAINEE_WRONG_RATING,

    GROUP_WRONG_NAME,
    GROUP_WRONG_ROOM,

    TRAINEE_NOT_FOUND,

    SCHOOL_WRONG_NAME,
    SCHOOL_WRONG_YEAR,

    DUPLICATE_GROUP_NAME,
    GROUP_NOT_FOUND,

    DUPLICATE_TRAINEE,

    EMPTY_TRAINEE_QUEUE,

    DUPLICATE_PASSPORT,
    PASSPORT_NOT_FOUND
}
